# Generated by Django 2.2.4 on 2019-08-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20190816_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Paper',
        ),
    ]
