# Generated by Django 2.2.4 on 2019-08-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_paper_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='published_at',
        ),
        migrations.AlterField(
            model_name='paper',
            name='web_link',
            field=models.CharField(max_length=600),
        ),
    ]
