# Generated by Django 2.2.4 on 2019-08-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20190816_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
